# Color
set -g default-terminal "screen-256color"

# No status bar
set-option -g status off

# Change from Ctrl-b to Ctrl-e
unbind C-b
set-option -g prefix C-e
bind C-e send-prefix

# Increase scrollback
set-option -g history-limit 50000

# Black and white
set-option -g status-style bg=grey,fg=black
set-option -g status-left-style bg=grey,fg=black
set-option -g status-right-style bg=grey,fg=black
set-option -g mode-style bg=grey,fg=black
set-option -g message-style bg=grey,fg=black
set-window-option -g window-status-style bg=white,fg=black
set-window-option -g window-status-current-style bg=grey,fg=black

# Window name
set-option -g automatic-rename on
set-environment -g TMUX_HOME "#{HOME}"
set-option -g automatic-rename-format '#{?#{!=:#{@window_name},},#{@window_name}:,#{host_short}:}#{s|^#{TMUX_HOME}|~|:pane_current_path}:#{pane_current_command}'
bind-key R command-prompt -I "#{@window_name}" -p "set window name:" "set-option -w @window_name '%%'"

# Move windows
bind-key . command-prompt -p "move window to:"  "swap-window -d -t '%%'"
