// Package hostcfg generates the host-side SSH material: the reusable ssh option
// set for reaching a sandbox by published port (keyed by HostKeyAlias so a
// recycled port never trips "host key changed"), and the managed
// ~/.ssh/config.d/cs-sandbox include that makes `ssh <name>` work.
package hostcfg

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/codesweep-ai/sandbox/internal/hostenv"
	"github.com/codesweep-ai/sandbox/internal/state"
)

// KnownHostsFile is the dedicated known-hosts file (keyed by HostKeyAlias) so
// managed connections never collide with the user's main known_hosts.
func KnownHostsFile(h hostenv.Host) string {
	return filepath.Join(h.SSHDir(), "known_hosts.cs-sandbox")
}

// SSHOptions returns the -o/-i/-p option list for reaching sandbox `name` on
// `port` with the user-tier key, keyed by HostKeyAlias.
func SSHOptions(h hostenv.Host, tierDir, name string, port int) []string {
	return []string{
		"-i", filepath.Join(tierDir, "id_cs-sandbox_user"),
		"-p", fmt.Sprintf("%d", port),
		"-o", "HostKeyAlias=" + name,
		"-o", "UserKnownHostsFile=" + KnownHostsFile(h),
		"-o", "StrictHostKeyChecking=accept-new",
		"-o", "IdentitiesOnly=yes",
	}
}

// SSHCommandString renders SSHOptions as a single `ssh …` string for
// GIT_SSH_COMMAND / core.sshCommand, so git transport reaches a sandbox without
// depending on the user's ssh config.
func SSHCommandString(h hostenv.Host, tierDir, name string, port int) string {
	parts := append([]string{"ssh"}, SSHOptions(h, tierDir, name, port)...)
	// Git runs this through a shell, so quote every argument containing shell
	// metacharacters. In particular, macOS keeps our keys under
	// "~/Library/Application Support/…".
	for i, p := range parts {
		parts[i] = shellQuote(p)
	}
	return strings.Join(parts, " ")
}

func shellQuote(s string) string {
	if s != "" && strings.IndexFunc(s, func(r rune) bool {
		return !(r >= 'a' && r <= 'z' ||
			r >= 'A' && r <= 'Z' ||
			r >= '0' && r <= '9' ||
			strings.ContainsRune("%+,-./:=@_", r))
	}) == -1 {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

// SyncSSHConfig regenerates ~/.ssh/config.d/cs-sandbox with one Host block per
// instance and ensures ~/.ssh/config includes it. It works off the typed state
// records, so containers and microVMs are written the same way.
func SyncSSHConfig(h hostenv.Host, tierDir string, insts []*state.Instance) error {
	if err := os.MkdirAll(h.SSHConfigDir(), 0o700); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Managed by cs-sandbox — do not edit. Regenerated by 'cs-sandbox sync-ssh-config'.\n")
	kh := KnownHostsFile(h)
	userKey := filepath.Join(tierDir, "id_cs-sandbox_user")
	idLines := h.IdentityLines() // host keys (H), if any
	for _, in := range insts {
		if in.Port == 0 {
			continue
		}
		fmt.Fprintf(&b, "\nHost %s\n", in.Name)
		fmt.Fprintf(&b, "    HostName 127.0.0.1\n")
		fmt.Fprintf(&b, "    Port %d\n", in.Port)
		fmt.Fprintf(&b, "    User %s\n", h.User)
		fmt.Fprintf(&b, "    HostKeyAlias %s\n", in.Name)
		// The host reaches sandboxes with its own keys (H) if it has any, plus the
		// user-tier key U (authorized in every sandbox) as a universal fallback.
		b.WriteString(idLines)
		fmt.Fprintf(&b, "    IdentityFile %s\n", hostenv.QuoteConfigArg(userKey))
		b.WriteString("    IdentitiesOnly yes\n")
		b.WriteString("    StrictHostKeyChecking accept-new\n")
		fmt.Fprintf(&b, "    UserKnownHostsFile %s\n", hostenv.QuoteConfigArg(kh))
	}
	if err := writeFileAtomic(h.SSHConfigFile(), []byte(b.String()), 0o600); err != nil {
		return err
	}
	return ensureInclude(h)
}

// ensureInclude prepends the Include directive to ~/.ssh/config if absent.
func ensureInclude(h hostenv.Host) error {
	cfg := filepath.Join(h.SSHDir(), "config")
	inc := "Include ~/.ssh/config.d/cs-sandbox"
	existing, err := os.ReadFile(cfg)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	for _, line := range strings.Split(string(existing), "\n") {
		if strings.TrimSpace(line) == inc {
			return nil
		}
	}
	merged := inc + "\n\n" + string(existing)
	return writeFileAtomic(cfg, []byte(merged), 0o600)
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) (err error) {
	// Preserve symlinked dotfile setups. Rename would otherwise replace the
	// symlink itself; resolving it lets us update the target atomically.
	if fi, lerr := os.Lstat(path); lerr == nil && fi.Mode()&os.ModeSymlink != 0 {
		resolved, rerr := filepath.EvalSymlinks(path)
		if rerr != nil {
			// Match os.WriteFile's behavior for a dangling symlink: follow it
			// and create the target when its parent exists.
			return os.WriteFile(path, data, mode)
		}
		path = resolved
	}
	f, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmp := f.Name()
	defer func() {
		_ = f.Close()
		_ = os.Remove(tmp)
	}()
	if err := f.Chmod(mode); err != nil {
		return err
	}
	if _, err := f.Write(data); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
