// Package hostcfg generates the host-side SSH material: the reusable ssh option
// set for reaching a sandbox by published port (keyed by HostKeyAlias so a
// recycled port never trips "host key changed"), and the managed
// ~/.ssh/config.d include that makes `ssh <name>` work.
package hostcfg

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/codesweep-ai/sandbox/internal/hostenv"
	"github.com/codesweep-ai/sandbox/internal/state"
)

// KnownHostsFile is the dedicated known-hosts file (keyed by HostKeyAlias) so
// managed connections never collide with the user's main known_hosts.
func KnownHostsFile(h hostenv.Host) string {
	return filepath.Join(h.SSHDir(), "known_hosts.cs-sandbox")
}

// SSHOptions returns the -o/-i/-p option list for reaching sandbox `name` on
// `port` with the user-tier key, keyed by HostKeyAlias.
func SSHOptions(h hostenv.Host, tierDir, name string, port int) []string {
	return []string{
		"-i", filepath.Join(tierDir, "id_cs-sandbox_user"),
		"-p", fmt.Sprintf("%d", port),
		"-o", "HostKeyAlias=" + name,
		"-o", "UserKnownHostsFile=" + KnownHostsFile(h),
		"-o", "StrictHostKeyChecking=accept-new",
		"-o", "IdentitiesOnly=yes",
	}
}

// SSHCommandString renders SSHOptions as a single `ssh …` string for
// GIT_SSH_COMMAND / core.sshCommand, so git transport reaches a sandbox without
// depending on the user's ssh config.
func SSHCommandString(h hostenv.Host, tierDir, name string, port int) string {
	parts := append([]string{"ssh"}, SSHOptions(h, tierDir, name, port)...)
	// Git runs this through a shell, so quote every argument containing shell
	// metacharacters. In particular, macOS keeps our keys under
	// "~/Library/Application Support/…".
	for i, p := range parts {
		parts[i] = shellQuote(p)
	}
	return strings.Join(parts, " ")
}

func shellQuote(s string) string {
	if s != "" && strings.IndexFunc(s, func(r rune) bool {
		return !(r >= 'a' && r <= 'z' ||
			r >= 'A' && r <= 'Z' ||
			r >= '0' && r <= '9' ||
			strings.ContainsRune("%+,-./:=@_", r))
	}) == -1 {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

// Ref is a sandbox's canonical, always-unambiguous ssh alias: <name>.<group>.
func Ref(in *state.Instance) string {
	g := in.Group
	if g == "" {
		g = state.DefaultGroup
	}
	return in.Name + "." + g
}

// GroupKeysDir maps the base key directory to one group's key directory. It
// mirrors paths.GroupKeys, kept here so hostcfg does not import paths.
func GroupKeysDir(tierBase, group string) string {
	return filepath.Join(tierBase, "groups", group)
}

// SyncSSHConfig regenerates this instances root's ~/.ssh/config.d fragment with
// one Host block per instance and ensures ~/.ssh/config includes it. It works
// off the typed state records, so containers and microVMs are written the same
// way. Only this root's fragment is touched: ~/.ssh is shared by every root on
// the host, so rewriting a single shared file would drop the Host blocks of
// sandboxes this root cannot see.
func SyncSSHConfig(h hostenv.Host, tierDir, instDir string, insts []*state.Instance, groups []*state.Group) error {
	if err := os.MkdirAll(h.SSHConfigDir(), 0o700); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Managed by cs-sandbox — do not edit. Regenerated by 'cs-sandbox sync-ssh-config'.\n")
	kh := KnownHostsFile(h)
	idLines := h.IdentityLines() // host keys (H), if any
	// A bare `ssh <name>` alias belongs to the default group and to nothing else,
	// matching how the CLI resolves a bare reference — so ssh and cs-sandbox can
	// never disagree about which sandbox a name denotes. Emitting it for whichever
	// group held the name uniquely made that meaning depend on the rest of the
	// host, and ssh_config takes the FIRST match for a keyword, so a later
	// collision would silently connect to whichever block was written first.
	blocks := 0
	// One gateway alias per group, plus a pattern that routes anything ending in
	// .<group> through it. The per-sandbox blocks below are the direct path and
	// keep working when a gateway is down; the jump host is what makes names
	// resolve the way they do INSIDE the group, and reaches services the
	// published SSH port does not.
	for _, g := range groups {
		if g.GWPort == 0 {
			continue
		}
		gwKey := filepath.Join(GroupKeysDir(tierDir, g.Name), "id_cs-sandbox_user")
		blocks++
		fmt.Fprintf(&b, "\nHost %s-gw\n", g.Name)
		fmt.Fprintf(&b, "    HostName 127.0.0.1\n")
		fmt.Fprintf(&b, "    Port %d\n", g.GWPort)
		fmt.Fprintf(&b, "    User %s\n", h.User)
		fmt.Fprintf(&b, "    HostKeyAlias %s-gw\n", g.Name)
		// Only the group key, deliberately: the gateway authorizes nothing else,
		// and offering the host's own identities first would exhaust sshd's
		// MaxAuthTries before this one was ever tried.
		fmt.Fprintf(&b, "    IdentityFile %s\n", hostenv.QuoteConfigArg(gwKey))
		b.WriteString("    IdentitiesOnly yes\n")
		b.WriteString("    StrictHostKeyChecking accept-new\n")
		fmt.Fprintf(&b, "    UserKnownHostsFile %s\n", hostenv.QuoteConfigArg(kh))
	}
	for _, in := range insts {
		if in.Port == 0 {
			continue
		}
		blocks++
		// Trust material is per group: the key that opens this sandbox opens
		// nothing in any other group.
		group := in.Group
		if group == "" {
			group = state.DefaultGroup
		}
		aliases := Ref(in)
		if group == state.DefaultGroup {
			aliases += " " + in.Name
		}
		userKey := filepath.Join(GroupKeysDir(tierDir, group), "id_cs-sandbox_user")
		fmt.Fprintf(&b, "\nHost %s\n", aliases)
		fmt.Fprintf(&b, "    HostName 127.0.0.1\n")
		fmt.Fprintf(&b, "    Port %d\n", in.Port)
		fmt.Fprintf(&b, "    User %s\n", h.User)
		fmt.Fprintf(&b, "    HostKeyAlias %s\n", Ref(in))
		// The host reaches sandboxes with its own keys (H) if it has any, plus the
		// group's user-tier key U as the fallback authorized in its members.
		b.WriteString(idLines)
		fmt.Fprintf(&b, "    IdentityFile %s\n", hostenv.QuoteConfigArg(userKey))
		b.WriteString("    IdentitiesOnly yes\n")
		b.WriteString("    StrictHostKeyChecking accept-new\n")
		fmt.Fprintf(&b, "    UserKnownHostsFile %s\n", hostenv.QuoteConfigArg(kh))
	}
	if blocks == 0 {
		// A root with nothing to describe leaves no fragment behind, so a
		// throwaway root does not litter ~/.ssh/config.d permanently.
		if err := os.Remove(h.SSHConfigFile(instDir)); err != nil && !os.IsNotExist(err) {
			return err
		}
		return ensureInclude(h)
	}
	if err := writeFileAtomic(h.SSHConfigFile(instDir), []byte(b.String()), 0o600); err != nil {
		return err
	}
	return ensureInclude(h)
}

// includeDirective is the one line cs-sandbox maintains in ~/.ssh/config. The
// pattern is a glob so a single directive covers every instances root's
// fragment; ssh reads glob matches in sorted order, so the default root (the
// plain name) wins if two roots use the same sandbox name.
const includeDirective = "Include ~/.ssh/config.d/cs-sandbox*"

// ensureInclude points ~/.ssh/config at the managed fragments: an Include of a
// cs-sandbox fragment is updated in place (keeping the user's ordering), and one
// is prepended if there is none.
func ensureInclude(h hostenv.Host) error {
	cfg := filepath.Join(h.SSHDir(), "config")
	existing, err := os.ReadFile(cfg)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	lines := strings.Split(string(existing), "\n")
	for i, line := range lines {
		if !isManagedInclude(line) {
			continue
		}
		if strings.TrimSpace(line) == includeDirective {
			return nil
		}
		lines[i] = includeDirective
		return writeFileAtomic(cfg, []byte(strings.Join(lines, "\n")), 0o600)
	}
	return writeFileAtomic(cfg, []byte(includeDirective+"\n\n"+string(existing)), 0o600)
}

// isManagedInclude reports whether a ~/.ssh/config line is the Include of a
// cs-sandbox fragment — the line this package owns and rewrites.
func isManagedInclude(line string) bool {
	f := strings.Fields(strings.TrimSpace(line))
	return len(f) == 2 && strings.EqualFold(f[0], "Include") &&
		strings.Contains(f[1], "config.d/cs-sandbox")
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) (err error) {
	// Preserve symlinked dotfile setups. Rename would otherwise replace the
	// symlink itself; resolving it lets us update the target atomically.
	if fi, lerr := os.Lstat(path); lerr == nil && fi.Mode()&os.ModeSymlink != 0 {
		resolved, rerr := filepath.EvalSymlinks(path)
		if rerr != nil {
			// Match os.WriteFile's behavior for a dangling symlink: follow it
			// and create the target when its parent exists.
			return os.WriteFile(path, data, mode)
		}
		path = resolved
	}
	f, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmp := f.Name()
	defer func() {
		_ = f.Close()
		_ = os.Remove(tmp)
	}()
	if err := f.Chmod(mode); err != nil {
		return err
	}
	if _, err := f.Write(data); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
